### ISSUE TITLE
Couple of errors

### ISSUE THREAD

**Issue by marcoelho97** [octolit/timeline#1]
Hello,

I have recently installed your timeline plugin, and I couldn’t really use it… When I attempt to create an entry it returned an error.

`"SQLSTATE[HY000]: General error: 1364 Field 'user' doesn't have a default value (SQL: insert into `octo_timeline_entries` (`title`, `date`, `time`, `text`, `public`) values (sadfa, 2017-01-04 18:00:04, 2017-01-31 12:00:00, <p>asdfasd</p>, 1))" on line 662 of /home/vagrant/Code/newproject/vendor/laravel/framework/src/Illuminate/Database/Connection.php`

Also, the component you drag into the page doesn’t work…

**Comment by octolit** [comment]
Thanks for submitting this issue. I have updated plugin to add fixes.

Also added default view for component. To use it please insert {% component 'entries' %} to your page.

Please let me know if you still facing problems.
